### ISSUE TITLE
Upgrade to walletconnect v2

### ISSUE THREAD

**Issue by wojtekwtf** [Prop-House/prop-house-monorepo#556]
Hi! Tried voting on prop house for my first time but it looks like it's trying to connect to wallet connect v1 which is now dead
<img width="1624" alt="Screenshot 2023-07-03 at 23 09 54" src="https://github.com/Prop-House/prop-house-monorepo/assets/10712818/f0217787-b9a4-4e32-bbc3-afedd17cf3ac">

I think here is an up to date example how to use v2 with rainbowkit: https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-app/app/providers.tsx

Happy to open a PR with a fix later, just raising for now in case this is already worked on

**Comment by cryptoseneca** [comment]
Hey Woj. Thanks for flagging - we will be upgrading soon!

**Comment by cdt-eth** [comment]
Closing: fixed via https://github.com/Prop-House/prop-house-monorepo/pull/603
